language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed engradwansalah/udagram-api-feed:v2

  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user engradwansalah/udagram-api-user:v2

  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend engradwansalah/udagram-frontend:v2
  
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag reverseproxy engradwansalah/reverseproxy:v2

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - docker logout
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push engradwansalah/udagram-api-feed:v2
  - docker push engradwansalah/udagram-api-user:v2
  - docker push engradwansalah/udagram-frontend:v2
  - docker push engradwansalah/reverseproxy:v2