apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
      - image: engradwansalah/reverseproxy:v3
        name: reverseproxy
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
      restartPolicy: Always

